-- Supabase schema for MiLiga
--
-- This is a pragmatic "migration starter" schema intended to get the app running.
-- Tighten RLS policies for production.

-- Extensions
create extension if not exists pgcrypto;

-- 1) Profiles (app-level user fields)
-- We store nickname/active group/role here instead of relying on auth.user_metadata.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  nickname text,
  role text not null default 'user',
  active_group_id uuid,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

-- Auto-create a profile row for new users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', null),
    coalesce(new.raw_user_meta_data->>'avatar_url', null)
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2) Players
create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  status text not null default 'active',
  avatar_url text,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

-- 3) Groups
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  host_id uuid references public.players(id) on delete set null,
  members uuid[] not null default '{}',
  invited_members uuid[] not null default '{}',
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

-- 4) Matches
create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  sport text,
  match_type text,
  sets_to_win int,
  location text,
  group_id uuid references public.groups(id) on delete set null,

  team1_name text,
  team2_name text,
  team1_players text[] default '{}',
  team2_players text[] default '{}',
  team1_player_refs jsonb default '[]'::jsonb,
  team2_player_refs jsonb default '[]'::jsonb,

  status text not null default 'live',
  winner text,

  team1_sets int default 0,
  team2_sets int default 0,
  team1_games int default 0,
  team2_games int default 0,
  team1_points text default '0',
  team2_points text default '0',
  total_points_team1 int default 0,
  total_points_team2 int default 0,

  -- History of completed sets; array of objects.
  set_history jsonb default '[]'::jsonb,

  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

-- 5) Events
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  location_name text,
  location_address text,
  event_datetime timestamptz not null,
  max_players int default 4,
  participants text[] default '{}',
  invited_users text[] default '{}',
  declined_users text[] default '{}',
  status text default 'open',
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

-- 6) App logs
create table if not exists public.app_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  page_name text not null,
  created_at timestamptz not null default now()
);

-- =============================================
-- Row Level Security (RLS)
-- =============================================

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.players enable row level security;
alter table public.groups enable row level security;
alter table public.matches enable row level security;
alter table public.events enable row level security;
alter table public.app_logs enable row level security;

-- PROFILES: users can read/update their own profile
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = user_id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = user_id);

-- PLAYERS/GROUPS/MATCHES/EVENTS: starter policies (authenticated CRUD)
-- IMPORTANT: tighten these for production (per-group membership, host/admin roles, etc.)
create policy "players_authenticated_read" on public.players
  for select using (auth.role() = 'authenticated');
create policy "players_authenticated_write" on public.players
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "groups_authenticated_read" on public.groups
  for select using (auth.role() = 'authenticated');
create policy "groups_authenticated_write" on public.groups
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "matches_authenticated_read" on public.matches
  for select using (auth.role() = 'authenticated');
create policy "matches_authenticated_write" on public.matches
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "events_authenticated_read" on public.events
  for select using (auth.role() = 'authenticated');
create policy "events_authenticated_write" on public.events
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- APP_LOGS: authenticated inserts for own user_id
create policy "app_logs_insert" on public.app_logs
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);
create policy "app_logs_select" on public.app_logs
  for select using (auth.role() = 'authenticated');
